name: Build and deploy Node.js app to Azure Web App - api-solucionesmota

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build
        working-directory: ./FastMailService/backend # Work in the backend directory
        run: |
          npm install
          npm run build  # Run the 'build' script (tsc)

      - name: Zip artifact for deployment
        working-directory: ./FastMailService/backend
        run: |
          zip -r ../../../release.zip ./dist ./package.json ./package-lock.json ./app.js  # Zip ONLY necessary files
          # Added app.js, if this is the entry point after the build, otherwise remove this line
          # If you have other top-level files in backend needed, add them here.

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'api-solucionesmota'
          slot-name: 'Production'
          package: . # Deploy from the current directory (root after unzipping)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6A4DB85C053649AE9062D181FB787D76 }}
